In [2]:
import pandas as pd

In [3]:

# Cargamos dataset
movies = pd.read_csv('../limpios/movieslimpio.csv')
credits = pd.read_csv('../limpios/creditslimpio.csv')

# Unimos datasets
df = pd.merge(movies, credits, on=['id', 'id'], how='inner')

In [4]:
df.head()

,belongs_to_collection,budget,genres,id,original_language,popularity,production_companies,production_countries,release_date,revenue,...,vote_average,vote_count,release_year,release_month,collection_name,return,character,actor_id,actor_name,Director
0,1,30000000.0,"['Animation', 'Comedy', 'Family']",862.0,en,21.946943,['Pixar Animation Studios'],['US'],1995-10-30,373554033.0,...,7.7,5415.0,1995,10,Toy Story Collection,12.451801,"['Woody (voice)', 'Buzz Lightyear (voice)', 'M...","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...",John Lasseter
1,0,65000000.0,"['Adventure', 'Fantasy', 'Family']",8844.0,en,17.015540,"['TriStar Pictures', 'Teitler Film', 'Intersco...",['US'],1995-12-15,262797249.0,...,6.9,2413.0,1995,12,None,4.043035,"['Alan Parrish', 'Samuel Alan Parrish / Van Pe...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",Joe Johnston
2,1,0.0,"['Romance', 'Comedy']",15602.0,en,11.712900,"['Warner Bros.', 'Lancaster Gate']",['US'],1995-12-22,0.0,...,6.5,92.0,1995,12,Grumpy Old Men Collection,0.000000,"['Max Goldman', 'John Gustafson', 'Ariel Gusta...","[6837, 3151, 13567, 16757, 589, 16523, 7166]","['Walter Matthau', 'Jack Lemmon', 'Ann-Margret...",Howard Deutch
3,0,16000000.0,"['Comedy', 'Drama', 'Romance']",31357.0,en,3.859495,['Twentieth Century Fox Film Corporation'],['US'],1995-12-22,81452156.0,...,6.1,34.0,1995,12,None,5.090760,"[""Savannah 'Vannah' Jackson"", ""Bernadine 'Bern...","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","['Whitney Houston', 'Angela Bassett', 'Loretta...",Forest Whitaker
4,1,0.0,['Comedy'],11862.0,en,8.387519,"['Sandollar Productions', 'Touchstone Pictures']",['US'],1995-02-10,76578911.0,...,5.7,173.0,1995,2,Father of the Bride Collection,0.000000,"['George Banks', 'Nina Banks', 'Franck Eggelho...","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","['Steve Martin', 'Diane Keaton', 'Martin Short...",Charles Shyer